name: Build Flutter iOS
description: Builds and uploads a signed XCArchive and IPA.

inputs:
  working-directory: {required: true, description: Flutter application directory}
  full-version: {required: true, description: Full pubspec version}

runs:
  using: composite
  steps:
    - name: Compile signed iOS archive
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flutter build ipa --release
    - name: Upload iOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-${{ inputs.full-version }}-${{ github.event.pull_request.head.sha || github.sha }}
        path: |
          ${{ inputs.working-directory }}/build/ios/archive/*.xcarchive
          ${{ inputs.working-directory }}/build/ios/ipa/*.ipa
        retention-days: 14
        if-no-files-found: error
