name: Build job / Flutter static analysis

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      flutter-version:
        type: string
        default: stable
      runner-labels:
        type: string
        default: '["self-hosted", "macOS", "ARM64"]'
    outputs:
      full-version:
        description: Version read from pubspec.yaml
        value: ${{ jobs.analysis.outputs.full-version }}

permissions:
  contents: read

jobs:
  analysis:
    name: Static analysis
    runs-on: ${{ fromJSON(inputs.runner-labels) }}
    timeout-minutes: 20
    outputs:
      full-version: ${{ steps.version.outputs.full-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout application
        uses: actions/checkout@v4
      - name: Setup Flutter SDK and dependencies
        uses: Juanpabedoyav/workflows/.github/actions/flutter/setup@v1
        with:
          flutter-version: ${{ inputs.flutter-version }}
          working-directory: ${{ inputs.working-directory }}
      - name: Read and validate application version
        uses: Juanpabedoyav/workflows/.github/actions/flutter/read-version@v1
        id: version
        with:
          working-directory: ${{ inputs.working-directory }}
      - name: Run Flutter static analysis
        run: flutter analyze
