name: Build job / Flutter Web

on:
  workflow_call:
    inputs:
      working-directory: {required: true, type: string}
      flutter-version: {type: string, default: stable}
      runner-labels: {type: string, default: '["self-hosted", "macOS", "ARM64"]'}
      full-version: {required: true, type: string}

permissions:
  contents: read

jobs:
  web:
    name: Web bundle
    runs-on: ${{ fromJSON(inputs.runner-labels) }}
    timeout-minutes: 25
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: Juanpabedoyav/workflows/.github/actions/flutter/setup@v1.0.1
        with:
          flutter-version: ${{ inputs.flutter-version }}
          working-directory: ${{ inputs.working-directory }}
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: web-${{ inputs.full-version }}-${{ github.sha }}
          path: ${{ inputs.working-directory }}/build/web
          retention-days: 14
          if-no-files-found: error
