name: Release integration / App Store

on:
  workflow_call:
    inputs:
      stage: {required: true, type: string}
      artifact-run-id: {type: string, default: ''}
      working-directory: {required: true, type: string}
      flutter-version: {type: string, default: stable}
      xcode-version: {type: string, default: default}
      runner: {type: string, default: self-hosted}
      runner-labels: {type: string, default: '["self-hosted", "macOS", "ARM64"]'}
      beta-command: {type: string, default: bundle exec fastlane ios beta}
      production-command: {type: string, default: bundle exec fastlane ios release}

permissions:
  actions: read
  contents: read

jobs:
  app-store:
    name: ${{ inputs.stage == 'beta' && 'TestFlight' || 'App Store production' }}
    environment: ${{ inputs.stage }}
    runs-on: ${{ fromJSON(inputs.runner-labels) }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        uses: Juanpabedoyav/workflows/.github/actions/flutter/setup-xcode@v3
        with:
          xcode-version: ${{ inputs.xcode-version }}
          runner: ${{ inputs.runner }}
      - uses: Juanpabedoyav/workflows/.github/actions/flutter/read-version@v3
        id: version
        with:
          working-directory: ${{ inputs.working-directory }}
      - name: Release iOS application
        uses: Juanpabedoyav/workflows/.github/actions/flutter/release-ios@v3
        with:
          stage: ${{ inputs.stage }}
          artifact-run-id: ${{ inputs.artifact-run-id }}
          working-directory: ${{ inputs.working-directory }}
          runner: ${{ inputs.runner }}
          app-version: ${{ steps.version.outputs.app-version }}
          build-number: ${{ steps.version.outputs.build-number }}
          full-version: ${{ steps.version.outputs.full-version }}
          app-store-connect-api-key-base64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
          app-store-connect-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          app-store-connect-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          app-store-locale: ${{ vars.APP_STORE_LOCALE }}
          app-store-description: ${{ vars.APP_STORE_DESCRIPTION }}
          app-store-keywords: ${{ vars.APP_STORE_KEYWORDS }}
          app-store-support-url: ${{ vars.APP_STORE_SUPPORT_URL }}
          app-store-release-notes: ${{ vars.APP_STORE_RELEASE_NOTES }}
          beta-command: ${{ inputs.beta-command }}
          production-command: ${{ inputs.production-command }}
